services:
  kafka:
    image: bashj79/kafka-kraft
    container_name: 'kafka'
    ports:
      - '9092:9092'
    environment:
      KAFKA_ENABLE_KRAFT: 'yes'
      ALLOW_PLAINTEXT_LISTENER: 'yes'
    volumes:
      - kafka_data:/opt/kafka/kafka-logs
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9092 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

volumes:
  kafka_data:
    driver: local