DATABASE_URL: "postgresql://esclient_devcomm:oBFG3H!7XYSJCSNK@pg4.sweb.ru:5433/esclient_devcomm"
HOST: "0.0.0.0"
PORT: "7006"

KAFKA_BROKERS: "localhost:9092"
KAFKA_REQUEST_TOPIC: "moderation-request"
KAFKA_RESULT_TOPIC: "moderation-result"
KAFKA_CONSUMER_GROUP_ID: "moderation-consumer-group"
KAFKA_MAX_RETRIES: "3"
KAFKA_RETRY_BACKOFF_MS: "1000"
KAFKA_ENABLE_SSL: false

LOG_LEVEL: "INFO"
LOG_FORMAT: "%(asctime)s %(levelname)-8s [%(name)s] %(message)s"
LOG_DATEFMT: "%Y-%m-%d %H:%M:%S"
