DATABASE_URL: "{vault:moderation-service/prod#database_url}"
HOST: "{vault:moderation-service/prod#host}"
PORT: "{vault:moderation-service/prod#port}"

KAFKA_BROKERS: "{vault:moderation-service/prod#kafka_brokers}"
KAFKA_REQUEST_TOPIC: "moderation-requests"
KAFKA_RESULT_TOPIC: "moderation-results"
KAFKA_CONSUMER_GROUP_ID: "moderation-service-group"
KAFKA_MAX_RETRIES: "5"
KAFKA_RETRY_BACKOFF_MS: "2000"
KAFKA_ENABLE_SSL: "{vault:moderation-service/prod#kafka_enable_ssl}"

LOG_LEVEL: "WARN"
LOG_FORMAT: "%(asctime)s %(levelname)-8s [%(name)s] %(message)s"
LOG_DATEFMT: "%Y-%m-%d %H:%M:%S"
